eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    lxl:
      path: /lxl/**
      serviceId: service-ribbon
    wdd:
      path: /wdd/**
      serviceId: service-feign
