stages:
- name: Build
  steps:
  - runScriptConfig:
      image: 192.168.186.13:8088/loner/maven-opjdk:v2
      shellScript: "cd euraker-service \nmvn clean install -Dmaven.test.skip=true"
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./euraker-service/Dockerfile
      buildContext: .
      tag: loner/eurakaer:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 192.168.186.13:8088
    env:
      PLUGIN_DEBUG: "true"      
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
notification: {}
